### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by markomni** [ChrisGrattoni/partitionoptimizer#1]
Every time I have tried running this on my data, I receive an error similar to this:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "SPOTS.py", line 3320, in run_parallel
    crossed_populations = cls.crossbreed_islands(island_populations, cls.number_of_processes, cls.number_of_tournament_reps_per_island)
  File "SPOTS.py", line 3173, in crossbreed_islands
    crossed_pop.extend(cls.get_crossed_children(first_pop, island_populations[-1], remainder, number_of_tournament_reps_per_island))
  File "SPOTS.py", line 3073, in get_crossed_children
    parent1 = population1[parent1_index][1]     # [1] is because we just want the partition part, not the score part
IndexError: list index out of range
```

Please let me know if you need to see any log files or my data set to determine what the cause is, or if there is something I should be doing differently than running it from the CLI.

Thanks!

**Comment by ChrisGrattoni** [comment]
Since it is an index error, I am guessing it is something to do with how
the data is formatted. If you send me your CSV file(s) I'd be happy to take
a look.
